apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "jenkins.fullname" . }}
  labels:
    app: {{ template "jenkins.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "jenkins.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "jenkins.fullname" . }}
    spec:
      containers:
      - env:
        - name: JENKINS_PASSWORD
          value: {{ .Values.rootPassword }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: jenkins
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 50000
          name: slavelistener
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        resources:
          requests:
             cpu: "500m"
             memory: "1024Mi"
      initContainers:
      - name: install-plugin
        image: {{ .Values.injector.image }}
        imagePullPolicy: {{ .Values.injector.imagePullPolicy }}
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
      - name: install-dsl-plugin
        image: {{ .Values.dsl.image }}
        imagePullPolicy: {{ .Values.dsl.imagePullPolicy }}
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      serviceAccount: {{ .Values.serviceAccount }}
      serviceAccountName: {{ .Values.serviceAccount }}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
      - name: {{ template "jenkins.fullname" . }}
      volumes:
      - name: jenkins-home
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "jenkins.fullname" . }}-data
      {{- else }}
        emptyDir: {}
      {{- end }}
