apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkins.fullname" . }}
  labels:
    app: {{ template "jenkins.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: http
    port: {{ .Values.httpPort | int }}
    targetPort: 8080
    nodePort: 30000
  - name: jnlp
    port: {{ .Values.jnlpPort | int }}
    targetPort: 50000
  selector:
    app: {{ template "jenkins.fullname" . }}