apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
  name: gitlab
spec:
  ports:
  - name: "1005"
    port: 1005
    targetPort: 80
  - name: "10022"
    port: 10022
    targetPort: 22
  selector:
status:
  loadBalancer: {}
