apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: gitlab
  name: gitlab
spec:
  ports:
  - name: "1005"
    port: 1005
    targetPort: 80
  - name: "10022"
    port: 10022
    targetPort: 22
  selector:
    io.kompose.service: gitlab
status:
  loadBalancer: {}
