apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitlab.fullname" . }}
  labels:
{{ include "gitlab.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: ssh
    port: {{ .Values.service.ports.ssh.port | int }}
    targetPort: ssh
    {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.ssh.nodePort }}
    nodePort: {{ .Values.service.ports.ssh.nodePort | int }}
    {{- end }}
  - name: http
    port: {{ .Values.service.ports.http.port | int }}
    targetPort: http
    {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.http.nodePort }}
    nodePort: {{ .Values.service.ports.http.nodePort | int }}
    {{- end }}
  - name: https
    port: {{ .Values.service.ports.https.port | int }}
    targetPort: https
    {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.https.nodePort }}
    nodePort: {{ .Values.service.ports.https.nodePort | int }}
    {{- end }}
  selector:
{{ include "gitlab.matchLabels" . | indent 4 }}