name: gitlab-ce
version: v0.1.1
appVersion: 11.3.5
description: GitLab Community Edition
keywords:
- git
- ci
- deploy
- issue tracker
- code review
- wiki
home: https://about.gitlab.com
sources:
- https://hub.docker.com/r/sameersbn/gitlab/
- https://github.com/sameersbn/docker-gitlab
icon: https://gitlab.com/uploads/group/avatar/6543/gitlab-logo-square.png
